apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-app
  labels:
    app: memory-stress-app
spec:
  restartPolicy: OnFailure
  containers:
  - name: memory-stress-app
    image: alexeiled/stress-ng
    imagePullPolicy: IfNotPresent
    command: ["/stress-ng"]
    args: ["--vm", "2", "--vm-bytes", "256M", "--metrics-brief", "--timeout", "48h", "-v", "--log-file", "/output/$(POD_NAME)-$(NODE_NAME).log", "--yaml", "/output/$(POD_NAME)-$(NODE_NAME).yaml" ]
    volumeMounts:
      - name: scratch-volume
        mountPath: /scratch
      - name: output-volume
        mountPath: /output
    resources:
      requests:
        cpu: 1
        memory: "5Gi"
      limits:
        cpu: 1
        memory: "5Gi"
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: REQ_CPU
        valueFrom:
          resourceFieldRef:
            containerName: memory-stress-app
            resource: requests.cpu
      - name: REQ_MEM
        valueFrom:
          resourceFieldRef:
            containerName: memory-stress-app
            resource: requests.memory
      - name: LIM_CPU
        valueFrom:
          resourceFieldRef:
            containerName: memory-stress-app
            resource: limits.cpu
      - name: LIM_MEM
        valueFrom:
          resourceFieldRef:
            containerName: memory-stress-app
            resource: limits.memory
  volumes:
    - name: scratch-volume
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi
    - name: output-volume
      hostPath:
        path: "/home/sysadmin/stress"