apiVersion: v1
kind: ConfigMap
metadata:
  name: kmm-hello-world-cm
  namespace: kernel-module-management
data:
  dockerfile: |
    FROM PLACEHOLDER_IMAGE as builder
    ARG KERNEL_FULL_VERSION
    RUN make KERNEL_DIR=/lib/modules/${KERNEL_FULL_VERSION}/build && \
        mkdir -p /opt/lib/modules/${KERNEL_FULL_VERSION} && \
        cp -v ./* /opt/lib/modules/${KERNEL_FULL_VERSION}
    RUN depmod -b /opt ${KERNEL_FULL_VERSION}