---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-releasenotes:
            vars:
              sphinx_python: python3
    gate:
      jobs:
        - build-openstack-releasenotes:
            vars:
              sphinx_python: python3
    post:
      jobs:
        - stx-test-upload-git-mirror

- job:
    name: stx-test-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/test to
      github.com/starlingx/test
    vars:
      git_mirror_repository: starlingx/test
    secrets:
      - name: git_mirror_credentials
        secret: stx-test-github-secret3
        pass-to-parent: true

- secret:
    name: stx-test-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - j2IjFNZzuuEGzEnQwLJSoz9NJnxB7Jtngu4W/qflm6x7OBi2vt71DB0h0ksF6IVNntD2s
          zNBZkzGPzvX2b7uxWx8Z1cB0PvUWnUc5VvjzdkLhBZW91fNxIc+JfBXR3lm7z3wJGqOJR
          TeiO4fLrecMZs0YMTXTtR7YSp9sz8HOKTi93S6MQHRvgv9Nxd/gbbLv8Ohl5S/Feu8N61
          cTgJCsyx/ra8yXrkefQBPFUCJyrM/kxnMVPBHbtCAxIzUK+4GguqJSpWbJkbsmKprEQCV
          EnhEFA87e4yixXQXT+eiTeM+qWcUbIEMkiql0kHcClWfMoB4TVB8oVnftEI4iM6f+plpF
          PfHFwySnN7XG0f9KxSQwUSexXWMeSTsoQiLg2LeKAzt6uFDh5vcMaZrvfYrr1QJDAzyfb
          dfwsq1FeRqncbl5YJTt1uaDMjtZbBH7JwTD7iC3rwXdKc+t+W2N8rpS4lBMUL/NGmJAo8
          vLS8gcc1vlqfznip7SlvMFdjQhnFcGso9q+unqs2TJ9HEq2mVmJSAHXzKQR3FtDZQ1FtJ
          0eNZG3bhRwEOA3keyCmglZds+fhbZbVtCMb4vncC4ASRBPzq91+9XXhHNPZQuMksrVrSm
          Efg8vjc9SFW4HYrZkjOBL+XhRS5O5r5HxrBiMRyYlOLkBhkYKAVvGE2GwnRot0=
        - WiUZQcGM7gnLa7oQKfFpLgVA//b8k8WKYoHWRlUBAHR/PPS54jN/MJvXC+XCGHtslSRBw
          SHcxKcHp8PVIj1WyNGL5e+lFMfInzWj8NX+E4Em2q2RA+Yup02I+aT0EMyLUINTANyPyC
          QlC2M+WYLnX4D5TFPOoTAww3rX2+4afOgRSYmDJ1BX2rpXW75yXWxU9TMHsV9QARlj2LP
          ELaYop4Sf0MHDldNYLdrcKwHC44/2cTbUWpWaHpmh+061b4AyJqDJXGSdWj1u81CP9Lwe
          M1Ia6nKkyYhsb23XYS0fFMP3ZjMskBMGJXwmh4Dzcrh4b0ajJ26kn9dppknX15oMhVUzl
          6llyhpnFYbcMCMMbn7hDNdvXw3YppFbdCk+ugfTVvXCKLDC9TsfYsEi+bvC5pCODbXYaO
          nssX7wOUvo6go3Qyzacf9TjoilkOuvn44m6+YdHLzygJW+3nkeaK6k3XKkPuLOdVjAP52
          RQ57j5qqXFB2mSk3OSMxBuQt8yVdfpMphIqvFfHW6pzt9hw3yES2on8R1eMAiRosaqOzY
          OsEwPEyHtYTxNyPNem9q+ZOX5Fq3UWStQPLxmEz26/4H1ZOBfTVemzRU4/WpQpEgId0kH
          42d9yeG79e/+Lo6tFqh538+pgq9A2OX+92MARSwgwirHE9+qvywoXqEEnXngTs=
        - HijXk7MLL4sZsFiOkIQ1pK+ipEKcthfPeGV/b0eZQ8gboZhtST+7ixuopsBlUZV5kBBu7
          dVYnEaRBleP0wvp/B5YZJK3a7QqunJiBA2USh6g3KrldsmpaYvo279S7sQaczrLRSCVLZ
          6DC/gGrUu4fEuSwLCoU67RfbFVH0ahiJcKNo0Tofi8i3Z7q0q9+HfJUoHD66oOR7NBbpF
          7qFl2FP18oMQqwyxLG8QuTfrJc00w0hKXmA/rdg/w3J7vz6IiY2eCW9RrlJCct89ifrKD
          6zjIdXjgxz+EzQpC9N3vpC5nPsiANkb5nJPu6ILDqpev9j1WdM/gm43FhDBzK3r8mC1by
          vLpOWw7XUq2BKtpkEYlY6HHx5URXC3nX/wNAKcAXSQh60A0Owg7bZ78Ij7H1/rJWEWti8
          HfMUlWtJCJxebSFBr0lQpzkMLiLS+IcVejbhhSfDFoAIWWacH4ohZWoF/n8IXbZ9FUld1
          gVRBTjVddLRVxqSj56ERV0P9lPGmHy48vynLSuFiiKDXH3gFLx2mcvN3JZTlL3GdFWtOQ
          SD+rwdjefqv7kxSapNxFoAMk+jaP1v/WfHortLhFiffOfQO75LDXsd89lnYojT30EQltj
          WI4IZ8goXfwVS+9CYe7toFpifxdWmwYPom1pJDsW0CNpi1WSxSeBg5FPf3NLnc=
        - ZVw6SMuGLnWF4bXwwREM6gljNMxtQCXtPy+K7Up/xzZbo6gUTm6jShIPtU3v3DAkgCEPH
          Q6CUgBuuDXR2KfqEwIniXFFgiAB/Wg6mEr+Qsx10YtLwjonm57aSQD7PIP9bwq5JLlPGn
          rBiNAJzFRxcgWuFusaKsvNYpIiZRoRaPPJX9n3hRhWdjcoh0BM5/a/xQKuaPgo08LG3Fl
          KjjmmFquyh5iKkhc/+x7OczUghKjZgqf8JdOKO4u2WmvFhW2Pm7qERqSMIR4E2JK8oC5Q
          gBWNykzMgy2Fn4OG4hnFv+6Nh23zFo8/kTwoqz+54gZauOxcpXipZ0NTk8tzj1/nrz+M5
          qkX/aGjqwCE0ojrk6NmkLW3UNtcxbg8D4RVxG6bxa4Ws3DqvKx+5VUhAbo6TWCwoK/Ykl
          EXB/U/M9WtgBQy2Dv2fW4P6GeNDpAaqvZIndhdUGb8jAmuPJza6Qk3Ri4GHXJo0oIxsLV
          9VRxOQeWxqK10M2Gcr60b4hDli87S1ZKKhxo9GBW0VBwuKromzTb2LPhwj3qI8flWkAQk
          lTF8oMCh6wVD1c6CgsXh58I2VFsZygPp/1HVqUeWNbQlfw/5Kazd7yH0qMGNkVzcqoqX1
          VKKyBDcAtZFgcZRAKL5c5DCTPycA1vud705ownji001/kBHyY2SL/BqvkbT6uU=
        - ucMMzIdo9c9cQaACRMdwKSHk0MEa/De376vWkvHI4dUDAPJycjPEDUwj8N6kxY2jwitwp
          w+nsSuN9U/56dl6AWYgsj3iO+vIoQdrTMBDfMeBAc7XFEoV0Vn3aKoZ/qc3vXpEAIu4PX
          Ez0y/1+aiCB6I9Ok9eYI4j/Yw/7MV2sbq2/v59AtaNoH140a8J5TSL7xl/vxvVavrqJNf
          RoSygw6YkS5QPPCoGaxWu9Xsba3jcnBRzH6Gq88ccbnFUfgOctbRQJwvl/UdVnqsDdRE5
          pMop1Osmki59t7yTc2zJuKvdpRUAQijNyBGXpImES4N3pOxZkt3uUV2cSO2VWyrYHvHPs
          +J0EQxoM2x9doLUIEM1jaBE+dfrmvNUZ4+80FE9cIWJN0RIfD6KeAuV7MKUi5P6kvf2Mv
          6zDd9kQuDZBxpf4Hy6+n61XNYP/tNgfvu+j9pJtaQ3r4kCmD3ID6T630CAcVqIcVOLM+q
          CDufyQFoxCDD+9RIUvewFSFBWWL8WVSTDDC25lWE77NCBOuip944EZQSjMgFDPM9OWpX7
          mhtEJBsHksNdB57chh9WkNYtoaeXiSSwPDuxlXhcEUxsHzf+m9BuT0s1huG07Wvt9jK1a
          ubOZV+Hbx/rWrQyb1ZtOmI23E/GQwIk/2M2lDEV+QfMVuo3uVzRmxVKnrJ70Aw=
        - Vn3qLQm0HNbJS9Nq/JhJnQeddzx8jaMJOwxKCCy13VpY8b2ufKaaf2xTmIV2YkOKPkoE6
          09g1TSbdN9Vc7ksKw7atIsa7KWEr6TJftyumsQSRcuU4hE1Gg+2XOh66MEMo19QRS+5kZ
          bYphJn2k0irBtDR4NUWFSR+5dNAv48PMopsMxMhuAkZUcbCQnWpnTOoCvpgj1gh5/FsuK
          i7173eR9N8iCBcH1zh1YlNSQA+LpBUl2w5eiSolLOh6B4K6VevtIJozEVMuLWsgjyc/Uc
          rvBZEP8mw6VtmdYsItmrs3kFc7oJTa/87N8IfsNIu1bi8+WyZYWKTYxg/9C0t6R9MqTHI
          XkH/qg0U3+vtNJSyf6q8mzZVGFx7k80+FaWe+FKBg6HKOk2KgCixRffY45TzgwMjhgrGa
          iG3Z/nUf7KaGuvvde/+/q1MuhUKXXK7Yo/EMa2dJhqdGDzF2ziWDCYAmyJ4fAjzhjIv7J
          bvFPHYGqbr8u8gbXu0vXADToEeS8q8LSZNAtM4KhwJGh2cbOiTy/gjZvJByuw1i83igGb
          fJTBy5f2QcYgzzyCrJ/bx8doODDmEqM26UW3xtLms/tzjmJys/tGWIWyyE1i6CxVnF4Q4
          EKrygYm/VmbsqtzOVbJyWxgNnHW1ikB9Z8CpGpjxGD11utAPxmiA8iyN6DeV00=
        - BHYUyhgPaEVUFtkt8KwMkbmP4qHPa0/RBjJ6IkrRoUXftX7+585Zn8Y1sgeURAGbuUC+g
          Fc+QAEDHj5aw6UFupziX3g+hBfqrKjgw/ZVInMqO+cN6taoE7NPYKdn508wCQsXE34DOR
          idw/L0OP9LS3acB6eH/P4zzpmif/uvM5daBLS3KgWUmQGZr68A/GMU+LDt4mV/Yv/9PJn
          i7m71Eb4+M7RFYG0D134T8f9WuzZJDO1gyDY/RoTRs3buXEK84AsReol5DAcWobB83cAb
          m58+YEndc8SYJVxB+cRuc84WKEAB1nxA63LV3qhI3PZK8F2OePUQPoxKpymMGnYMB0N/4
          2Y2/8kmygzmwB+2QJZ7INk0l57kIs21hN59NFZAsTcEEds3w3EsJjZY+T0hp3fyxYA+5i
          K4gjrl9DbUnZDAk99HZmwklfYaklGNe5oeHO4Slpbzirl+BX475sZw2QxDyiraL8zib0Y
          yk6YC1RGw9S70ZwS1maj8but4RN29HG1Q2FgAKBV6eRP2cA6Pwv+3WN3O5eeuzHOCElWG
          k0e32DtKZYTFp34H0Zme1tnlgAxcG4rYj76NkNs1ZqbbwapMyPOuU1nkAnKx3lDRp0GSZ
          /C4Fy3gCnWs0Px62q1l9c6e568WBl2Js2dFRv1cBp6J7Z6ENjjK0HCbFJnXXzM=
