[tool.isort]
py_version = "311"
profile = "black"

[tool.black]
target-version = ['py311']
preview = true
include = '\.py'

[tool.pydoclint]
style = "google"
check-return-types = true
allow-init-docstring = true
