apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-cirros-1
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {% for hostname in compute_hostnames %}
                - {{ hostname }}
                {% endfor %}
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
        resources:
          requests:
            memory: 128Mi
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
        name: containerdisk
