apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: debian1280
  name: debian1280
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: debian1280
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        resources:
          requests:
            memory: 1Gi
      volumes:
      - dataVolume:
          name: debian1280qcow
        name: datavolumedisk
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            password: password
            chpasswd:
              expire: false
            ssh_pwauth: true
        name: cloudinitdisk
