apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dell-nfs-writer-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-powerstore-nfs
