apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: stepca-issuer
    kubernetes.io/ingress.class: nginx
  name: kuard
  namespace: pvtest
spec:
  rules:
  - host: '{{ dns_name }}'
    http:
      paths:
      - backend:
          service:
            name: kuard
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - '{{ dns_name }}'
    secretName: kuard-ingress-tls