---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvol0
  namespace: dell-storage
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-powerstore-iscsi
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: powerstoretest
    namespace: dell-storage
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: powerstoretest
    namespace: dell-storage
spec:
    serviceName: powerstoretest
    selector:
        matchLabels:
          app: powerstoretest
    template:
      metadata:
        labels:
          app: powerstoretest
      spec:
        serviceAccount: powerstoretest
        hostNetwork: true
        containers:
          - name: test
            image: quay.io/centos/centos:latest
            command: [ "/bin/sleep", "3600" ]
            volumeMounts:
              - mountPath: "/data0"
                name: pvol0
        volumes:
          - name: pvol0
            persistentVolumeClaim:
              claimName: pvol0
