---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvol0
  namespace: dell-storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-powerstore-nfs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: powerstoretest
  namespace: dell-storage
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: powerstoretest
  namespace: dell-storage
spec:
  serviceName: powerstoretest
  selector:
    matchLabels:
      app: powerstoretest
  template:
    metadata:
      labels:
        app: powerstoretest
    spec:
      serviceAccount: powerstoretest
      hostNetwork: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 30
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - controller-0
      containers:
        - name: test
          image: quay.io/centos/centos:latest
          command: ["/bin/sleep", "7200"]
          volumeMounts:
            - mountPath: "/data0"
              name: pvol0
      volumes:
        - name: pvol0
          persistentVolumeClaim:
            claimName: pvol0
