apiVersion: v1
kind: Pod
metadata:
  name: static-cpu-pod
spec:
  runtimeClassName: kata
  containers:
    - name: static-cpu-container
      image: nginx:stable-alpine
      resources:
        requests:
          cpu: "1"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "256Mi"
