apiVersion: v1
kind: Namespace
metadata:
  name: test-node-affinity-namespace
---

apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-to-compute-pod
  namespace: test-node-affinity-namespace
  labels:
    app: node-affinity-example
spec:
  containers:
  - name: nginx
    image: nginx:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "node-role.kubernetes.io/control-plane"
            operator: DoesNotExist