apiVersion: apps/v1
kind: Deployment
metadata:
  name: small
  labels:
    app: small
spec:
  replicas: 1
  selector:
    matchLabels:
      app: small
  template:
    metadata:
      labels:
        app: small
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
        name: small
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"
      restartPolicy: Always