apiVersion: v1
kind: Pod
metadata:
  name: calicoctl
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do sleep 3600; done
    env:
    - name: DATASTORE_TYPE
      value: kubernetes
    image: registry.local:9001/calico-ctl
    name: calicoctl
  hostNetwork: true
  imagePullSecrets:
  - name: default-registry-key
  nodeSelector:
    beta.kubernetes.io/os: linux
  serviceAccountName: calicoctl

