apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: netdev-sriov
  name: test-sriovdp-netdev-connectivity-ipv6-0
spec:
  containers:
  - args:
    - while true; do sleep 300000; done;
    command:
    - /bin/sh
    - -c
    - --
    image: registry.local:9001/pv-test
    imagePullPolicy: IfNotPresent
    name: test-sriovdp-netdev-connectivity-ipv6-0
    resources:
      limits:
        intel.com/pci_sriov_net_group0_data1: 1
      requests:
        intel.com/pci_sriov_net_group0_data1: 1
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        - NET_ADMIN
        - NET_RAW
  nodeSelector:
    kubernetes.io/hostname: controller-0
  imagePullSecrets:
    - name: local-secret

