apiVersion: v1
kind: Pod
metadata:
 name: baseline-pod-deny
 namespace: baseline-ns
spec:
 containers:
 - name: pause
   image: registry.local:9001/pause
   securityContext:
     privileged: true
 imagePullSecrets:
 - name: local-secret