apiVersion: v1
kind: Pod
metadata:
  name: restricted-pod-deny
  namespace: restricted-ns
spec:
  containers:
    - name:  pause
      image: registry.local:9001/pause
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
           - ALL
  imagePullSecrets:
  - name: local-secret