apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        cpu: 0
        memory: "256Mi"
      limits:
        cpu: 1
        memory: "256Mi"
  nodeSelector:
    kubernetes.io/hostname: controller-0
