apiVersion: apps/v1
kind: Deployment
metadata:
  name: besteffort
  labels:
    app: besteffort
spec:
  replicas: 5
  selector:
    matchLabels:
      app: besteffort
  template:
    metadata:
      labels:
        app: besteffort
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
        name: besteffort
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
