---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: lvmcsi-snapshot
driver: topolvm.io
deletionPolicy: Delete
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: lvmcsi-pvc-snapshot-dedicated
spec:
  volumeSnapshotClassName: lvmcsi-snapshot
  source:
    persistentVolumeClaimName: lvm-snap-pvc-lvm-provisioner
