apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lvm-pvc-lvm-provisioner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvm-provisioner
  resources:
    requests:
      storage: 1Gi
