apiVersion: v1
kind: Pod
metadata:
  name: dsa-accel-config-demo
  labels:
    app: dsa-accel-config-demo
spec:
  containers:
  - name: dsa-accel-config-demo
    image: registry.local:9001/starlingx/stx-debian-tools-dev:stx.10.0-v1.0.0
    imagePullPolicy: "Always"
    workingDir: "/usr/libexec/accel-config/test/"
    command:
      - "./dsa_user_test_runner.sh"
    args:
      - "--skip-config"
    resources:
      limits:
        # dsa.intel.com/wq-user-dedicated: 1
        # In kernels 5.13-5.17, ENQCMD is disabled (is to be reinstated in 5.18)
        dsa.intel.com/wq-user-shared: 1
    securityContext:
      capabilities:
        add:
          ["SYS_RAWIO"]
  restartPolicy: Never
  imagePullSecrets:
  - name: default-registry-key

